### ISSUE TITLE
new cannons and pipeworks

### ISSUE THREAD

**Issue by SwissalpS** [mt-mods/spacecannon#21]
Do the new cannons not support pipeworks by design or just because it hasn't been added yet?  
Asking before submitting PR only to be told that they shouldn't support it ;)

**Comment by BuckarooBanzay** [comment]
i don't see a problem with that, would be a great addition :+1:

**Comment by kiedtl** [comment]
It's an oversight, yes, I had initially assumed pipework would work automatically with any node having an inventory (especially those with only one).

**Comment by SwissalpS** [comment]
while working on this I noticed that cables are supposed to connect to all sides.  I tried removing bottom, which is the side of the muzzle.  
Somehow connects_to list does not work. No matter which combo I tried.

Another curiosity I found: the purple cannon shoots through a HV cable if the cable is directly in front of the muzzle :P
